const { pgTable, serial, text, numeric, timestamp, jsonb, integer } = require('drizzle-orm/pg-core');

const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  password_hash: text('password_hash').notNull(),
  created_at: timestamp('created_at').defaultNow(),
});

const invoices = pgTable('invoices', {
  id: serial('id').primaryKey(),
  user_id: integer('user_id').references(() => users.id),
  invoice_number: text('invoice_number').notNull(),
  company_name: text('company_name'),
  company_address: text('company_address'),
  company_address2: text('company_address2'),
  company_phone: text('company_phone'),
  company_email: text('company_email'),
  company_website: text('company_website'),
  issue_date: text('issue_date'),
  due_date: text('due_date'),
  customer_name: text('customer_name'),
  customer_address: text('customer_address'),
  customer_phone: text('customer_phone'),
  customer_email: text('customer_email'),
  services: jsonb('services'),
  billing_mode: text('billing_mode'),
  gst_percent: numeric('gst_percent', { precision: 5, scale: 2 }),
  hst_percent: numeric('hst_percent', { precision: 5, scale: 2 }),
  discount: numeric('discount', { precision: 10, scale: 2 }),
  bank_name: text('bank_name'),
  account_number: text('account_number'),
  transit_number: text('transit_number'),
  institution_number: text('institution_number'),
  director_name: text('director_name'),
  director_title: text('director_title'),
  logo_data: text('logo_data'),
  signature_data: text('signature_data'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

const quotations = pgTable('quotations', {
  id: serial('id').primaryKey(),
  user_id: integer('user_id').references(() => users.id),
  quote_number: text('quote_number').notNull(),
  company_name: text('company_name'),
  company_address: text('company_address'),
  company_phone: text('company_phone'),
  company_email: text('company_email'),
  company_website: text('company_website'),
  quote_date: text('quote_date'),
  valid_until: text('valid_until'),
  project_type: text('project_type'),
  client_name: text('client_name'),
  contact_person: text('contact_person'),
  client_address: text('client_address'),
  client_email: text('client_email'),
  intro_text: text('intro_text'),
  terms: text('terms'),
  services: jsonb('services'),
  billing_mode: text('billing_mode'),
  gst_percent: numeric('gst_percent', { precision: 5, scale: 2 }),
  hst_percent: numeric('hst_percent', { precision: 5, scale: 2 }),
  discount: numeric('discount', { precision: 10, scale: 2 }),
  bank_name: text('bank_name'),
  account_number: text('account_number'),
  transit_number: text('transit_number'),
  institution_number: text('institution_number'),
  director_name: text('director_name'),
  director_title: text('director_title'),
  logo_data: text('logo_data'),
  signature_data: text('signature_data'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

module.exports = { users, invoices, quotations };
